"""add plant identification models

Revision ID: 26c2c2246794
Revises: 
Create Date: 2026-08-10 20:19:00.694005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c2c2246794'
down_revision: Union[str, Sequence[str], None] = '7bc7020964bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_identifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'complete', 'needs_more_photos', name='identificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identification_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identification_id', sa.String(), nullable=False),
    sa.Column('species_id', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.Enum('high', 'moderate', 'low', name='confidencelabel'), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identification_id'], ['plant_identifications.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_annotations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identification_id', sa.String(), nullable=False),
    sa.Column('image_ref', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identification_id'], ['plant_identifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identification_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('annotation_id', sa.String(), nullable=True),
    sa.Column('supports_or_contradicts', sa.Enum('supports', 'contradicts', name='evidencedirection'), nullable=False),
    sa.Column('explanation_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['image_annotations.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['identification_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite doesn't support ALTER TABLE ADD CONSTRAINT at all — batch
    # mode is required here (it uses SQLite's copy-and-move strategy
    # under the hood). This also works correctly on Postgres, so it's
    # the right approach for both dialects, not a SQLite-only workaround.
    with op.batch_alter_table('user_plants') as batch_op:
        batch_op.create_foreign_key(
            'fk_user_plants_source_identification_id',
            'plant_identifications',
            ['source_identification_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plants') as batch_op:
        batch_op.drop_constraint('fk_user_plants_source_identification_id', type_='foreignkey')
    op.drop_table('identification_evidence')
    op.drop_table('image_annotations')
    op.drop_table('identification_candidates')
    op.drop_table('plant_identifications')
    # ### end Alembic commands ###