"""create core garden and plant tables
 
Revision ID: 4fab27d38e78
Revises: 
Create Date: 2026-07-17 20:31:59.875495
 
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4fab27d38e78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    '''Upgrade schema.'''
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_species',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('common_name', sa.String(), nullable=False),
                    sa.Column('scientific_name', sa.String(), nullable=False),
                    sa.Column('category', sa.String(), nullable=True),
                    sa.Column('native_status', sa.String(), nullable=True),
                    sa.Column('toxicity_notes', sa.String(), nullable=True),
                    sa.Column('invasive_flag', sa.Boolean(), nullable=False),
                    sa.Column('taxonomy_source', sa.String(), nullable=True),
                    sa.Column('synonyms', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('scientific_name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('display_name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('gardens',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('garden_type', sa.Enum('raised_bed', 'in_ground', 'container', 'indoor', 'greenhouse', 'hydroponic', 'community', 'orchard', 'lawn', 'landscape_bed', name='gardentype'), nullable=False),
                    sa.Column('sunlight_exposure', sa.String(), nullable=True),
                    sa.Column('soil_type', sa.String(), nullable=True),
                    sa.Column('soil_ph', sa.Float(), nullable=True),
                    sa.Column('drainage', sa.String(), nullable=True),
                    sa.Column('irrigation_method', sa.String(), nullable=True),
                    sa.Column('notes', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('plant_varieties',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('species_id', sa.String(), nullable=False),
                    sa.Column('variety_name', sa.String(), nullable=False),
                    sa.Column('days_to_maturity', sa.Integer(), nullable=True),
                    sa.Column('notes', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_beds',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('garden_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('is_container', sa.Boolean(), nullable=False),
                    sa.Column('dimensions', sa.String(), nullable=True),
                    sa.Column('container_size', sa.String(), nullable=True),
                    sa.Column('bed_depth', sa.String(), nullable=True),
                    sa.Column('notes', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_locations',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('garden_id', sa.String(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('resolved_address', sa.String(), nullable=True),
                    sa.Column('usda_zone', sa.String(), nullable=True),
                    sa.Column('estimated_last_frost', sa.Date(), nullable=True),
                    sa.Column('estimated_first_frost', sa.Date(), nullable=True),
                    sa.Column('zone_source', sa.String(), nullable=True),
                    sa.Column('frost_source', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('garden_id')
    )
    op.create_table('user_plants',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('species_id', sa.String(), nullable=False),
                    sa.Column('variety_id', sa.String(), nullable=True),
                    sa.Column('nickname', sa.String(), nullable=True),
                    sa.Column('source_identification_id', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['variety_id'], ['plant_varieties.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('garden_bed_id', sa.String(), nullable=False),
                    sa.Column('user_plant_id', sa.String(), nullable=False),
                    sa.Column('planting_method', sa.Enum('indoor_seed_start', 'direct_sow', 'transplant', name='plantingmethod'), nullable=False),
                    sa.Column('indoor_start_date', sa.Date(), nullable=True),
                    sa.Column('transplant_date', sa.Date(), nullable=True),
                    sa.Column('direct_sow_date', sa.Date(), nullable=True),
                    sa.Column('estimated_germination_window', sa.String(), nullable=True),
                    sa.Column('estimated_maturity_window', sa.String(), nullable=True),
                    sa.Column('estimated_harvest_window', sa.String(), nullable=True),
                    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['garden_bed_id'], ['garden_beds.id'], ),
                    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    '''Downgrade schema.'''
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantings')
    op.drop_table('user_plants')
    op.drop_table('garden_locations')
    op.drop_table('garden_beds')
    op.drop_table('plant_varieties')
    op.drop_table('gardens')
    op.drop_table('users')
    op.drop_table('plant_species')
    # ### end Alembic commands ###