"""add growing requirement fields to plant_species

Revision ID: 7bc7020964bf
Revises: 7c8217386ad1
Create Date: 2026-07-26 03:07:00.694399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc7020964bf'
down_revision: Union[str, Sequence[str], None] = '4fab27d38e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_species', sa.Column('sunlight_requirement', sa.Enum('full_sun', 'partial_sun', 'partial_shade', 'full_shade', name='sunlightrequirement'), nullable=True))
    op.add_column('plant_species', sa.Column('water_requirement', sa.Enum('low', 'moderate', 'high', name='waterrequirement'), nullable=True))
    op.add_column('plant_species', sa.Column('frost_tolerance', sa.Enum('frost_sensitive', 'half_hardy', 'hardy', name='frosttolerance'), nullable=True))
    op.add_column('plant_species', sa.Column('spacing_inches', sa.Float(), nullable=True))
    op.add_column('plant_species', sa.Column('soil_ph_min', sa.Float(), nullable=True))
    op.add_column('plant_species', sa.Column('soil_ph_max', sa.Float(), nullable=True))
    op.add_column('plant_species', sa.Column('germination_days_min', sa.Integer(), nullable=True))
    op.add_column('plant_species', sa.Column('germination_days_max', sa.Integer(), nullable=True))
    op.add_column('plant_species', sa.Column('maturity_days_min', sa.Integer(), nullable=True))
    op.add_column('plant_species', sa.Column('maturity_days_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant_species', 'maturity_days_max')
    op.drop_column('plant_species', 'maturity_days_min')
    op.drop_column('plant_species', 'germination_days_max')
    op.drop_column('plant_species', 'germination_days_min')
    op.drop_column('plant_species', 'soil_ph_max')
    op.drop_column('plant_species', 'soil_ph_min')
    op.drop_column('plant_species', 'spacing_inches')
    op.drop_column('plant_species', 'frost_tolerance')
    op.drop_column('plant_species', 'water_requirement')
    op.drop_column('plant_species', 'sunlight_requirement')
    # ### end Alembic commands ###